### ISSUE TITLE
I can't find how to specify version

### ISSUE THREAD

**Issue by hornta** [CatChen/versioned-storage#249]
I need a way to specify the version of the data so that I can write my migration scripts, that would be nice to have a part of this library.

**Comment by CatChen** [comment]
@hornta Thanks for the suggestion. Can you elaborate more on how you would imagine that API?

**Comment by CatChen** [comment]
@hornta I've improved the API so you can read data from existing storage (regardless of version) and then migrate it. Please see the example in README. That you for your feature request.
